server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL:127.0.0.1}:${MYSQL_PORT:3306}/dynamic_excel?serverTimeZone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PWD:123456}
logging:
  level:
    sql: info
    web: info
  file:
    path: ./log/excel
springdoc:
  api-docs:
    # 是否开启文档功能，默认为true，可不配置
    enabled: true
  swagger-ui:
    # 访问ip:port/api，可直接访问Swagger springdoc
    path: /api
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 字段映射为 javaBean时，自动转驼峰，而不用配置 @TableField
    map-underscore-to-camel-case: true
  global-config:
    # 刷新mapper 调试神器
    db-config:
      # 表名、是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: true
      # 逻辑已删除值(默认为 1)
      logic-delete-value: true
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: false